#!/bin/sh -e
#
#    session_name: print the screen name in the panel
#
#    Copyright (C) 2013 Ramasamy Chandramouli
#
#    Authors: Ramasamy Chandramouli <rchandramouli@live.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Find session name in TMUX based sessions
__session_tmux() {
	local sname=
	local count=
	local sock=

	sname=$(tmux display-message -p '#S')

	count=$(echo "$TMUX" | grep -o , | wc -l)
	count=$((count-1))

	sock="$(echo $TMUX | cut -f1-$count -d,)"
	sock=$(basename "$sock")

	printf "%s/%s" "$sock" "$sname"
}

# Find session name in SCREEN based sessions
__session_screen() {
	local sname=

	sname="$(byobu-screen -ls | grep -e ^[[:space:]]$1. | cut -f2)"

	printf "%s" "$sname"
}

__session_name() {
	local lpid=$PPID
	local sname=

	if [ -n "$TMUX" ]; then
	    sname="$(__session_tmux $lpid)"
	else
	    sname="$(__session_screen $lpid)"
	fi
	printf " "; color b r W; printf "-"; printf "%s-" "$sname"; color --
}
